// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:2084
    public enum ImDrawCornerFlags_
    {
        _None = 0x0,
        _TopLeft = 0x1,
        _TopRight = 0x2,
        _BotLeft = 0x4,
        _BotRight = 0x8,
        _Top = 0x3,
        _Bot = 0xc,
        _Left = 0x5,
        _Right = 0xa,
        _All = 0xf,
    }
}
