// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:2098
    public enum ImDrawListFlags_
    {
        _None = 0x0,
        _AntiAliasedLines = 0x1,
        _AntiAliasedFill = 0x2,
        _AllowVtxOffset = 0x4,
    }
}
