// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:2318
    public enum ImFontAtlasFlags_
    {
        _None = 0x0,
        _NoPowerOfTwoHeight = 0x1,
        _NoMouseCursors = 0x2,
    }
}
