// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:925
    public enum ImGuiPopupFlags_
    {
        _None = 0x0,
        _MouseButtonLeft = 0x0,
        _MouseButtonRight = 0x1,
        _MouseButtonMiddle = 0x2,
        _MouseButtonMask_ = 0x1f,
        _MouseButtonDefault_ = 0x1,
        _NoOpenOverExistingPopup = 0x20,
        _NoOpenOverItems = 0x40,
        _AnyPopupId = 0x80,
        _AnyPopupLevel = 0x100,
        _AnyPopup = 0x180,
    }
}
