// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:966
    public enum ImGuiTabBarFlags_
    {
        _None = 0x0,
        _Reorderable = 0x1,
        _AutoSelectNewTabs = 0x2,
        _TabListPopupButton = 0x4,
        _NoCloseWithMiddleMouseButton = 0x8,
        _NoTabListScrollingButtons = 0x10,
        _NoTooltip = 0x20,
        _FittingPolicyResizeDown = 0x40,
        _FittingPolicyScroll = 0x80,
        _FittingPolicyMask_ = 0xc0,
        _FittingPolicyDefault_ = 0x40,
    }
}
