// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1005
    public enum ImGuiHoveredFlags_
    {
        _None = 0x0,
        _ChildWindows = 0x1,
        _RootWindow = 0x2,
        _AnyWindow = 0x4,
        _AllowWhenBlockedByPopup = 0x8,
        _AllowWhenBlockedByActiveItem = 0x20,
        _AllowWhenOverlapped = 0x40,
        _AllowWhenDisabled = 0x80,
        _RectOnly = 0x68,
        _RootAndChildWindows = 0x3,
    }
}
