// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1158
    public enum ImGuiConfigFlags_
    {
        _None = 0x0,
        _NavEnableKeyboard = 0x1,
        _NavEnableGamepad = 0x2,
        _NavEnableSetMousePos = 0x4,
        _NavNoCaptureKeyboard = 0x8,
        _NoMouse = 0x10,
        _NoMouseCursorChange = 0x20,
        _DockingEnable = 0x40,
        _ViewportsEnable = 0x400,
        _DpiEnableScaleViewports = 0x4000,
        _DpiEnableScaleFonts = 0x8000,
        _IsSRGB = 0x100000,
        _IsTouchScreen = 0x200000,
    }
}
