// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1381
    public enum ImGuiCond_
    {
        _None = 0x0,
        _Always = 0x1,
        _Once = 0x2,
        _FirstUseEver = 0x4,
        _Appearing = 0x8,
    }
}
