// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:993
    public enum ImGuiFocusedFlags_
    {
        _None = 0x0,
        _ChildWindows = 0x1,
        _RootWindow = 0x2,
        _AnyWindow = 0x4,
        _RootAndChildWindows = 0x3,
    }
}
