// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:941
    public enum ImGuiSelectableFlags_
    {
        _None = 0x0,
        _DontClosePopups = 0x1,
        _SpanAllColumns = 0x2,
        _AllowDoubleClick = 0x4,
        _Disabled = 0x8,
        _AllowItemOverlap = 0x10,
    }
}
