// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1301
    public enum ImGuiColorEditFlags_
    {
        _None = 0x0,
        _NoAlpha = 0x2,
        _NoPicker = 0x4,
        _NoOptions = 0x8,
        _NoSmallPreview = 0x10,
        _NoInputs = 0x20,
        _NoTooltip = 0x40,
        _NoLabel = 0x80,
        _NoSidePreview = 0x100,
        _NoDragDrop = 0x200,
        _NoBorder = 0x400,
        _AlphaBar = 0x10000,
        _AlphaPreview = 0x20000,
        _AlphaPreviewHalf = 0x40000,
        _HDR = 0x80000,
        _DisplayRGB = 0x100000,
        _DisplayHSV = 0x200000,
        _DisplayHex = 0x400000,
        _Uint8 = 0x800000,
        _Float = 0x1000000,
        _PickerHueBar = 0x2000000,
        _PickerHueWheel = 0x4000000,
        _InputRGB = 0x8000000,
        _InputHSV = 0x10000000,
        __OptionsDefault = 0xa900000,
        __DisplayMask = 0x700000,
        __DataTypeMask = 0x1800000,
        __PickerMask = 0x6000000,
        __InputMask = 0x18000000,
        _RGB = 0x100000,
        _HSV = 0x200000,
        _HEX = 0x400000,
    }
}
