// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1266
    public enum ImGuiStyleVar_
    {
        _Alpha = 0x0,
        _WindowPadding = 0x1,
        _WindowRounding = 0x2,
        _WindowBorderSize = 0x3,
        _WindowMinSize = 0x4,
        _WindowTitleAlign = 0x5,
        _ChildRounding = 0x6,
        _ChildBorderSize = 0x7,
        _PopupRounding = 0x8,
        _PopupBorderSize = 0x9,
        _FramePadding = 0xa,
        _FrameRounding = 0xb,
        _FrameBorderSize = 0xc,
        _ItemSpacing = 0xd,
        _ItemInnerSpacing = 0xe,
        _IndentSpacing = 0xf,
        _ScrollbarSize = 0x10,
        _ScrollbarRounding = 0x11,
        _GrabMinSize = 0x12,
        _GrabRounding = 0x13,
        _TabRounding = 0x14,
        _ButtonTextAlign = 0x15,
        _SelectableTextAlign = 0x16,
        _COUNT = 0x17,
        _Count_ = 0x17,
    }
}
