// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:982
    public enum ImGuiTabItemFlags_
    {
        _None = 0x0,
        _UnsavedDocument = 0x1,
        _SetSelected = 0x2,
        _NoCloseWithMiddleMouseButton = 0x4,
        _NoPushId = 0x8,
        _NoTooltip = 0x10,
    }
}
