// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1085
    public enum ImGuiKey_
    {
        _Tab = 0x0,
        _LeftArrow = 0x1,
        _RightArrow = 0x2,
        _UpArrow = 0x3,
        _DownArrow = 0x4,
        _PageUp = 0x5,
        _PageDown = 0x6,
        _Home = 0x7,
        _End = 0x8,
        _Insert = 0x9,
        _Delete = 0xa,
        _Backspace = 0xb,
        _Space = 0xc,
        _Enter = 0xd,
        _Escape = 0xe,
        _KeyPadEnter = 0xf,
        _A = 0x10,
        _C = 0x11,
        _V = 0x12,
        _X = 0x13,
        _Y = 0x14,
        _Z = 0x15,
        _COUNT = 0x16,
    }
}
