// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1183
    public enum ImGuiBackendFlags_
    {
        _None = 0x0,
        _HasGamepad = 0x1,
        _HasMouseCursors = 0x2,
        _HasSetMousePos = 0x4,
        _RendererHasVtxOffset = 0x8,
        _PlatformHasViewports = 0x400,
        _HasMouseHoveredViewport = 0x800,
        _RendererHasViewports = 0x1000,
    }
}
