// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1036
    public enum ImGuiDragDropFlags_
    {
        _None = 0x0,
        _SourceNoPreviewTooltip = 0x1,
        _SourceNoDisableHover = 0x2,
        _SourceNoHoldToOpenOthers = 0x4,
        _SourceAllowNullID = 0x8,
        _SourceExtern = 0x10,
        _SourceAutoExpirePayload = 0x20,
        _AcceptBeforeDelivery = 0x400,
        _AcceptNoDrawDefaultRect = 0x800,
        _AcceptNoPreviewTooltip = 0x1000,
        _AcceptPeekOnly = 0xc00,
    }
}
