// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1358
    public enum ImGuiMouseCursor_
    {
        _None = unchecked((int)0xffffffff),
        _Arrow = 0x0,
        _TextInput = 0x1,
        _ResizeAll = 0x2,
        _ResizeNS = 0x3,
        _ResizeEW = 0x4,
        _ResizeNESW = 0x5,
        _ResizeNWSE = 0x6,
        _Hand = 0x7,
        _NotAllowed = 0x8,
        _COUNT = 0x9,
        _Count_ = 0x9,
    }
}
