// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:2609
    public enum ImGuiViewportFlags_
    {
        _None = 0x0,
        _NoDecoration = 0x1,
        _NoTaskBarIcon = 0x2,
        _NoFocusOnAppearing = 0x4,
        _NoFocusOnClick = 0x8,
        _NoInputs = 0x10,
        _NoRendererClear = 0x20,
        _TopMost = 0x40,
        _Minimized = 0x80,
        _NoAutoMerge = 0x100,
        _CanHostOtherWindows = 0x200,
    }
}
