// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:871
    public enum ImGuiInputTextFlags_
    {
        _None = 0x0,
        _CharsDecimal = 0x1,
        _CharsHexadecimal = 0x2,
        _CharsUppercase = 0x4,
        _CharsNoBlank = 0x8,
        _AutoSelectAll = 0x10,
        _EnterReturnsTrue = 0x20,
        _CallbackCompletion = 0x40,
        _CallbackHistory = 0x80,
        _CallbackAlways = 0x100,
        _CallbackCharFilter = 0x200,
        _AllowTabInput = 0x400,
        _CtrlEnterForNewLine = 0x800,
        _NoHorizontalScroll = 0x1000,
        _AlwaysInsertMode = 0x2000,
        _ReadOnly = 0x4000,
        _Password = 0x8000,
        _NoUndoRedo = 0x10000,
        _CharsScientific = 0x20000,
        _CallbackResize = 0x40000,
        _Multiline = 0x100000,
        _NoMarkEdited = 0x200000,
    }
}
