// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:899
    public enum ImGuiTreeNodeFlags_
    {
        _None = 0x0,
        _Selected = 0x1,
        _Framed = 0x2,
        _AllowItemOverlap = 0x4,
        _NoTreePushOnOpen = 0x8,
        _NoAutoOpenOnLog = 0x10,
        _DefaultOpen = 0x20,
        _OpenOnDoubleClick = 0x40,
        _OpenOnArrow = 0x80,
        _Leaf = 0x100,
        _Bullet = 0x200,
        _FramePadding = 0x400,
        _SpanAvailWidth = 0x800,
        _SpanFullWidth = 0x1000,
        _NavLeftJumpsBackHere = 0x2000,
        _CollapsingHeader = 0x1a,
    }
}
