// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1074
    public enum ImGuiDir_
    {
        _None = unchecked((int)0xffffffff),
        _Left = 0x0,
        _Right = 0x1,
        _Up = 0x2,
        _Down = 0x3,
        _COUNT = 0x4,
    }
}
