// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1348
    public enum ImGuiMouseButton_
    {
        _Left = 0x0,
        _Right = 0x1,
        _Middle = 0x2,
        _COUNT = 0x5,
    }
}
