// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1023
    public enum ImGuiDockNodeFlags_
    {
        _None = 0x0,
        _KeepAliveOnly = 0x1,
        _NoDockingInCentralNode = 0x4,
        _PassthruCentralNode = 0x8,
        _NoSplit = 0x10,
        _NoResize = 0x20,
        _AutoHideTabBar = 0x40,
    }
}
