// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1113
    public enum ImGuiKeyModFlags_
    {
        _None = 0x0,
        _Ctrl = 0x1,
        _Shift = 0x2,
        _Alt = 0x4,
        _Super = 0x8,
    }
}
