// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:952
    public enum ImGuiComboFlags_
    {
        _None = 0x0,
        _PopupAlignLeft = 0x1,
        _HeightSmall = 0x2,
        _HeightRegular = 0x4,
        _HeightLarge = 0x8,
        _HeightLargest = 0x10,
        _NoArrowButton = 0x20,
        _NoPreview = 0x40,
        _HeightMask_ = 0x1e,
    }
}
