// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1058
    public enum ImGuiDataType_
    {
        _S8 = 0x0,
        _U8 = 0x1,
        _S16 = 0x2,
        _U16 = 0x3,
        _S32 = 0x4,
        _U32 = 0x5,
        _S64 = 0x6,
        _U64 = 0x7,
        _Float = 0x8,
        _Double = 0x9,
        _COUNT = 0xa,
    }
}
