// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:1126
    public enum ImGuiNavInput_
    {
        _Activate = 0x0,
        _Cancel = 0x1,
        _Input = 0x2,
        _Menu = 0x3,
        _DpadLeft = 0x4,
        _DpadRight = 0x5,
        _DpadUp = 0x6,
        _DpadDown = 0x7,
        _LStickLeft = 0x8,
        _LStickRight = 0x9,
        _LStickUp = 0xa,
        _LStickDown = 0xb,
        _FocusPrev = 0xc,
        _FocusNext = 0xd,
        _TweakSlow = 0xe,
        _TweakFast = 0xf,
        _KeyMenu_ = 0x10,
        _KeyLeft_ = 0x11,
        _KeyRight_ = 0x12,
        _KeyUp_ = 0x13,
        _KeyDown_ = 0x14,
        _COUNT = 0x15,
        _InternalStart_ = 0x10,
    }
}
