// This source code was generated by ClangCaster

namespace UI
{
    // ../../imgui/imgui.h:827
    public enum ImGuiWindowFlags_
    {
        _None = 0x0,
        _NoTitleBar = 0x1,
        _NoResize = 0x2,
        _NoMove = 0x4,
        _NoScrollbar = 0x8,
        _NoScrollWithMouse = 0x10,
        _NoCollapse = 0x20,
        _AlwaysAutoResize = 0x40,
        _NoBackground = 0x80,
        _NoSavedSettings = 0x100,
        _NoMouseInputs = 0x200,
        _MenuBar = 0x400,
        _HorizontalScrollbar = 0x800,
        _NoFocusOnAppearing = 0x1000,
        _NoBringToFrontOnFocus = 0x2000,
        _AlwaysVerticalScrollbar = 0x4000,
        _AlwaysHorizontalScrollbar = 0x8000,
        _AlwaysUseWindowPadding = 0x10000,
        _NoNavInputs = 0x40000,
        _NoNavFocus = 0x80000,
        _UnsavedDocument = 0x100000,
        _NoDocking = 0x200000,
        _NoNav = 0xc0000,
        _NoDecoration = 0x2b,
        _NoInputs = 0xc0200,
        _NavFlattened = 0x800000,
        _ChildWindow = 0x1000000,
        _Tooltip = 0x2000000,
        _Popup = 0x4000000,
        _Modal = 0x8000000,
        _ChildMenu = 0x10000000,
        _DockNodeHost = 0x20000000,
    }
}
