// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2046
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImDrawVert
    {

        public Vector2 pos;
        public Vector2 uv;
        public uint col;
    }
}
