// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2114
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImDrawList
    {

        public IntPtr CmdBuffer;
        public IntPtr IdxBuffer;
        public IntPtr VtxBuffer;
        public int Flags;
        public IntPtr _Data;
        public IntPtr _OwnerName;
        public uint _VtxCurrentIdx;
        public IntPtr _VtxWritePtr;
        public IntPtr _IdxWritePtr;
        public IntPtr _ClipRectStack;
        public IntPtr _TextureIdStack;
        public IntPtr _Path;
        public ImDrawCmd _CmdHeader;
        public ImDrawListSplitter _Splitter;
    }
}
