// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2251
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImFontConfig
    {

        public IntPtr FontData;
        public int FontDataSize;
        public bool FontDataOwnedByAtlas;
        public int FontNo;
        public float SizePixels;
        public int OversampleH;
        public int OversampleV;
        public bool PixelSnapH;
        public Vector2 GlyphExtraSpacing;
        public Vector2 GlyphOffset;
        public IntPtr GlyphRanges;
        public float GlyphMinAdvanceX;
        public float GlyphMaxAdvanceX;
        public bool MergeMode;
        public uint RasterizerFlags;
        public float RasterizerMultiply;
        public ushort EllipsisChar;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 40)] public sbyte[] Name;
        public IntPtr DstFont;
    }
}
