// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2280
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImFontGlyph
    {

        public uint Codepoint;
        public uint Visible;
        public float AdvanceX;
        public float X0;
        public float Y0;
        public float X1;
        public float Y1;
        public float U0;
        public float V0;
        public float U1;
        public float V1;
    }
}
