// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2306
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImFontAtlasCustomRect
    {

        public ushort Width;
        public ushort Height;
        public ushort X;
        public ushort Y;
        public uint GlyphID;
        public float GlyphAdvanceX;
        public Vector2 GlyphOffset;
        public IntPtr Font;
    }
}
