// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2342
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImFontAtlas
    {

        public bool Locked;
        public int Flags;
        public IntPtr TexID;
        public int TexDesiredWidth;
        public int TexGlyphPadding;
        public IntPtr TexPixelsAlpha8;
        public IntPtr TexPixelsRGBA32;
        public int TexWidth;
        public int TexHeight;
        public Vector2 TexUvScale;
        public Vector2 TexUvWhitePixel;
        public IntPtr Fonts;
        public IntPtr CustomRects;
        public IntPtr ConfigData;
        [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)] public int[] CustomRectIds;
    }
}
