// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2291
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImFontGlyphRangesBuilder
    {

        public IntPtr UsedChars;
    }
}
