// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:2627
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImGuiViewport
    {

        public uint ID;
        public int Flags;
        public Vector2 Pos;
        public Vector2 Size;
        public Vector2 WorkOffsetMin;
        public Vector2 WorkOffsetMax;
        public float DpiScale;
        public IntPtr DrawData;
        public uint ParentViewportId;
        public IntPtr RendererUserData;
        public IntPtr PlatformUserData;
        public IntPtr PlatformHandle;
        public IntPtr PlatformHandleRaw;
        public bool PlatformRequestMove;
        public bool PlatformRequestResize;
        public bool PlatformRequestClose;
    }
}
