// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:1732
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImGuiWindowClass
    {

        public uint ClassId;
        public uint ParentViewportId;
        public int ViewportFlagsOverrideSet;
        public int ViewportFlagsOverrideClear;
        public int DockNodeFlagsOverrideSet;
        public int DockNodeFlagsOverrideClear;
        public bool DockingAlwaysTabBar;
        public bool DockingAllowUnclassed;
    }
}
