// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:218
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImVec2
    {

        public float x;
        public float y;
    }
}
