// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/imgui.h:231
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ImVec4
    {

        public float x;
        public float y;
        public float z;
        public float w;
    }
}
