// This source code was generated by ClangCaster
using System;
using System.Runtime.InteropServices;
using System.Numerics;

namespace UI
{
    // ../../imgui/examples/imgui_impl_dx11.h:17
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct ID3D11DeviceContext
    {

    }
}
