// This source code was generated by ClangCaster

namespace UI
{
    public static partial class C
    {
        // ../../imgui/imgui.h:64
        public const int IMGUI_VERSION_NUM = unchecked((int)17602);

        // ../../imgui/imgui.h:66
        public const int IMGUI_HAS_VIEWPORT = unchecked((int)1);

        // ../../imgui/imgui.h:67
        public const int IMGUI_HAS_DOCK = unchecked((int)1);

        // ../../imgui/imgui.h:1809
        public const int IM_UNICODE_CODEPOINT_INVALID = unchecked((int)0xFFFD);

        // ../../imgui/imgui.h:1813
        public const int IM_UNICODE_CODEPOINT_MAX = unchecked((int)0xFFFF);

        // ../../imgui/imgui.h:1965
        public const int IM_COL32_R_SHIFT = unchecked((int)0);

        // ../../imgui/imgui.h:1966
        public const int IM_COL32_G_SHIFT = unchecked((int)8);

        // ../../imgui/imgui.h:1967
        public const int IM_COL32_B_SHIFT = unchecked((int)16);

        // ../../imgui/imgui.h:1968
        public const int IM_COL32_A_SHIFT = unchecked((int)24);

        // ../../imgui/imgui.h:1969
        public const int IM_COL32_A_MASK = unchecked((int)0xFF000000);

        // ../../imgui/imgui.h:2017
        public const int ImDrawCallback_ResetRenderState = unchecked((int)( - 1 ));

    }
}
